[package]
name = "masterchat_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
urlencoding = "2.1.2"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
sha1_smol = "1.0.0"
